### ISSUE TITLE
Since the release of 1.0.0 the .github/workflows/release-iso.yml in "startingpoint" (and derivatives) has been broken

### ISSUE THREAD

**Issue by dperson** [ublue-os/isogenerator#15]
Fully up to date (rebased on top of latest template repo from upstream as of 2024-02-19).

I've tried using the "1.0.0" version and just no version for the isogenerator.

---

- Expected behavior:
It generates an install ISO

- Actual behavior:
Generates these lgos for "Generate and Release ISOs"
```
Current runner version: '2.313.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `ublue-os/isogenerator@v2.3.1`, unable to find version `v2.3.1`
```

- Reproducibility:
Every time

- Steps to reproduce:
Kick off a build of a "startingpoint" based image

---

Thanks, love ublue!

**Comment by noelmiller** [comment]
This is due to us replacing the old [isogenerator](https://github.com/ublue-os/isogenerator-old) repo with this new repo. With this new approach, we can build fully offline ISOs with this Github Action.

**Comment by dperson** [comment]
Should I update my release-iso.yml to model the test-iso.yml then? And once it's working, submit a PR for startingpoint?

**Comment by xynydev** [comment]
Note that ublue-os/main [suffers from the same error](https://github.com/ublue-os/main/actions/runs/7978898463/job/21785059240). All custom image template repos have been updated to use isogenerator-old until we rewrite the ISO release workflow as a reusable github action

**Comment by noelmiller** [comment]
Per the recent announcement, we are no longer creating ISO images for main. This is due to the ISOs being a lot bigger than the original net installer and we cannot host them for free on Github Releases. If you want to create ISO images for your images, you will need to retool to either use this project or the original project we forked from.
