### ISSUE TITLE
Remote gets assigned to :38 and not the tag

### ISSUE THREAD

**Issue by castrojo** [ublue-os/isogenerator#2]
I followed jason's instructions: 

```
docker run -it --privileged fedora:latest
dnf install -y make git
git clone https://github.com/ublue-os/isogenerator.git
make install-deps
make image_name=base-main
```

I did `make image_name=bluefin version=38 image_tag=gts`

AND IT ALL WORKED -- AMAZING!!!

Only issue is the remote is assigned to `bluefin:38`, and we want that to be `bluefin:gts`

```
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:38
                   Digest: sha256:084992f8b844fb762ade706c68761a97b1f203e1f8ce27b6419ca8e7602279be
                  Version: 38.20240215.0 (2024-02-15T16:48:06Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:38
                   Digest: sha256:084992f8b844fb762ade706c68761a97b1f203e1f8ce27b6419ca8e7602279be
                  Version: 38.20240215.0 (2024-02-15T16:48:06Z)

```

**Comment by noelmiller** [comment]
We reverted @bsherman's fix. I will take a look at this when I get back from lunch. I think it's part of the solution, just not the whole thing.

**Comment by bsherman** [comment]
> We reverted @bsherman's fix. I will take a look at this when I get back from lunch.

I'm tinkering with this a bit locally as well. I wasn't too hopeful on the simple change, but was fun to try.
