### ISSUE TITLE
Add support for ISO image media checks 

### ISSUE THREAD

**Issue by p5** [ublue-os/isogenerator#23]
When installing the ISO, the default GRUB boot entry is to "Verify media and install".  When selecting this option, the media check fails since no checksum is present.

![image](https://github.com/ublue-os/isogenerator/assets/46304672/6a138aa3-db2c-4d10-949b-99b3f0291687)

Apologies, I can't easily grab the text from the screenshot

**Comment by noelmiller** [comment]
No worries! We'll take a look. It's not something I tested during the development phase.

**Comment by noelmiller** [comment]
For now, we are going to work around this by removing the option to do it. We may add this in the future as a feature, but I'd have to do a lot of research to figure out how the feature works :)
