### ISSUE TITLE
Support action usage outside UBlue

### ISSUE THREAD

**Issue by p5** [ublue-os/isogenerator#32]
It would be good to expose options like secure boot keys so the action can be used by others to build ISOs in their personal images.

Right now, the only hard-coded ublueified configuration I could find (and cannot be overwritten) is for secure boot cert enrollment.

**Comment by JasonN3** [comment]
I'm going to back to developing on the original repo, so anyone else will be able to use that as it's going to be setup for anyone to use that wants to a containerized OSTree

**Comment by KyleGospo** [comment]
> It would be good to expose options like secure boot keys so the action can be used by others to build ISOs in their personal images.
> 
> Right now, the only hard-coded ublueified configuration I could find (and cannot be overwritten) is for secure boot cert enrollment.

Agreed, now that we have working ISOs I'm all for minor enhancements like this. The key to be applied should be broken into a build arg, with no key specified meaning no enrollment action.
