### ISSUE TITLE
Support Kernel Args from inputs

### ISSUE THREAD

**Issue by p5** [ublue-os/isogenerator#51]
It would be good if we can configure kargs for the image to do things like disabling Nouveau drivers in Nvidia images.
In the previous ISO generator, kickstart did this.  Not sure how it would work here.

**Comment by noelmiller** [comment]
EXTRA_BOOT_PARAMS does this: https://github.com/ublue-os/isogenerator/blob/c5f825fd3ebd2538e1f051c31c4d04d7b6d4c3b6/Makefile#L8

Used here in Bazzite: https://github.com/ublue-os/bazzite/blob/f216e4c5fd68c8d927fc8664c4167dcce634850c/.github/workflows/build_iso.yml#L40

This adds to grub lines here: https://github.com/ublue-os/isogenerator/blob/c5f825fd3ebd2538e1f051c31c4d04d7b6d4c3b6/Makefile#L69
