### ISSUE TITLE
Support for Podman

### ISSUE THREAD

**Issue by boredsquirrel** [ublue-os/isogenerator#52]
The creation guide only shows Docker, while it should probably be compatible with with Podman?

But when I try I always get this error

```
~ ❯❯❯ docker run --rm --privileged --volume .:/isogenerator/output -e VERSION=39 -e IMAGE_NAME=kinoite-main -e IMAGE_TAG=latest -e VARIANT=Kinoite ghcr.io/ublue-os/isogenerator:39    ✘ 125
Trying to pull ghcr.io/ublue-os/isogenerator:39...
Error: Source image rejected: A signature was required, but no signature exists
~ ❯❯❯ podman run --disable-content-trust --rm --privileged --volume .:/isogenerator/output -e VERSION=39 -e IMAGE_NAME=kinoite-main -e IMAGE_TAG=latest -e VARIANT=Kinoite ghcr.io/ublue-os/isogenerator:39
Trying to pull ghcr.io/ublue-os/isogenerator:39...
Error: Source image rejected: A signature was required, but no signature exists
```

I am not sure if this is a bug as I dont have Docker installed. So this is a FR to support Podman, as its preinstalled everywhere, especially on atomic Fedora variants, unlike Docker.

But this also seems like a bug somewhere.

**Comment by xynydev** [comment]
There are `podman` run instructions in the README

The issue you are facing is an issue with container signing and `/etc/containers/policy.json`.

**Comment by noelmiller** [comment]
README has been updated to include podman support. Containers should also be signed properly now too. I'm going to close this, feel free to reopen if you continue to have issues.
